### PR TITLE
Github Actions

### PR DESCRIPTION
**Pull request by tijko**
Start of _Github-Actions_ pipeline for build release to aid with AUR packaging.

### CODE REVIEW

**Comment by kinnay** [comment]
Thanks for the effort. Would you mind explaining a few things?

If I understand correctly, this runs whenever something is pushed to the master branch. In that case, the netlink package is installed, the installed package is archived, and uploaded to github as a release draft.

What I'm curious about is:

1. How did you come up with `netlink-bin-x86_64-${TAG:1}`? Is this some kind of standard naming convention? I would assume that we want to distribute the source, rather than a binary build.
2. Since the job runs on multiple different Python versions, which one will be uploaded as a release draft?

I also just looked it up on your fork, and it appears that the last two steps are failing. This can probably be resolved by adding a git tag though.

Besides that, the badge in the README currently refers to your fork. I think it would make more sense if it pointed to my repository instead.

**Comment by tijko** [comment]
Thanks for your response and quick reply.

Having been researching the "release" action just last night I have been testing this and working out different aspects.

I had mistakenly opened the PR to your `master` branch last night (I don't care for Github's default to go upstream, instead of the local fork).  So I needed to get this merged into my `master` branch but figured it wasn't a huge hassle to get it open on yours as well.

You picked up on the "Release Draft" as I had thought that was going to just upload the binary and provide an endpoint.  As far as the binary, to be honest I was just collaborating with another dev on another package to maintain.  I almost had blinders on at that point using some of what they showed me on this.

As far as point "2".. I was going to ask what your preference (if any) was on this. 

Besides that I was just going to work out a few of the spots (mainly the ones you noticed) and finish it up.

**Comment by kinnay** [comment]
Alright, let me know when you think that it is ready to merge.

> As far as point "2".. I was going to ask what your preference (if any) was on this.

I have to admit that I don't have much experience. The package only contains Python source, which should be the same for every Python version. In general, I would say that targeting the latest Python version makes the most sense, but again, as far as I'm aware the build will be the same for every version.

I'm also not yet sure how uploading a release draft is going to help with publishing an Arch package, but I am curious to learn!

**Comment by tijko** [comment]
>The package only contains Python source, which should be the same for every Python version. In general, I would say that targeting the latest Python version makes the most sense, but again, as far as I'm aware the build will be the same for every version.

Latest version it is.  To be honest, I had thought the "test-matrix" was the way to go here.  I wasn't sure but I thought there might be slight differences, between Python 3.7 vs 3.11 for example.  Or was this just Py2 vs Py3?  Either way I'll pin down a version and stick with it.

The release draft was just an added step (feature?) of the Github Action I was using to get the source available as an endpoint.  This ultimately will serve as an endpoint that can be uploaded through the `makepkg` tool.  So long as it has a maintained `PKGBUILD` the package will be available through the Archlinux User Repo tools (e.g. `yay -S python-netlink` will install it). 

I'll definitely be picking up a few things too.  I was wanting to be sure that we are referring to the same thing.  When you say "Draft Release" that means the posting of "notes" and other information and not just having a URL to an archive of the files needed to run `netlink` install?

**Comment by tijko** [comment]
Got pretty busy earlier this week but this latest change should do it.

I listed all of the fixes, including the one for the "Release Draft".  Apparently that is a default setting that gets pushed out automatically by the Github Action (https://github.com/softprops/action-gh-release).

https://github.com/tijko/netlink/pull/2#issue-2291159893 (for the full list of issues fixed)

With this "release" archive in place it will make maintaining for Archlinux pretty simple.

So we can then possibly build and improve the package itself (I've done some Netlink programming) and I'm interested in seeing how this can be done.

**Comment by tijko** [comment]
Going over some other projects and researching different methods and approaches.  I came across a tool called ["backupninja"](https://github.com/funilrys/aur-backupninja-git/tree/master/.github/workflows).

It might serve to give some perspective of what I had in mind.

And to make sure I add in, I was interested in the Netlink subsystem itself primarily and wanted to start to write some code for the module.  Having this setup first was a good first step I thought.

**Comment by kinnay** [comment]
Unfortunately I do not have any time this week or next week but I am going to take a look at your changes later. 👍

**Comment by kinnay** [comment]
I'm still curious if this is really the best way to set up AUR packaging, but we'll see.

**Comment by tijko** [comment]
> I'm still curious if this is really the best way to set up AUR packaging, but we'll see.

What are your trepidations?

Honestly, I researched a few other projects on AUR.  I also followed the wiki but for the most part I read through established Python packages.

I'm on mobile so putting up links is not practical right now but I can put up references to the process later.

**Comment by kinnay** [comment]
My remark was just a general fear of the unknown. Sorry about that.

**Comment by tijko** [comment]
> My remark was just a general fear of the unknown. Sorry about that.

There's no apology necessary.  I feel very lucky that you even responded.  Honestly, I wouldn't have been insulted because that's just how things go sometimes with Open Source projects.  You've been really cool about doing this and I'm pretty excited that we can get something going and possibly have a solid piece of code that can be useful and contribute to the ecosystem.

Especially with the recent events in other PyPI projects and the whole `xz` situation you have every right to be skeptical about having people pop up on your project page.

I have been very busy lately but hopefully I can make some progress with communicating some of this to other developers on the Archlinux project and we can make sure everything is closely inspected and done right.

**Pull request merged**
